package ms.MyBatisSample.entity.jsv;

public class Cities {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsv.cities.city_id
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    private String cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsv.cities.city_name
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsv.cities.location
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    private String location;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsv.cities.city_id
     *
     * @return the value of jsv.cities.city_id
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsv.cities.city_id
     *
     * @param cityId the value for jsv.cities.city_id
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsv.cities.city_name
     *
     * @return the value of jsv.cities.city_name
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsv.cities.city_name
     *
     * @param cityName the value for jsv.cities.city_name
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsv.cities.location
     *
     * @return the value of jsv.cities.location
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsv.cities.location
     *
     * @param location the value for jsv.cities.location
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }
}