package ms.MyBatisSample.entity.jsv;

import java.util.Date;

public class Weather extends WeatherKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsv.weather.city_id
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    private String cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsv.weather.temp_lo
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    private Integer tempLo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsv.weather.temp_hi
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    private Integer tempHi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsv.weather.prcp
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    private Integer prcp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsv.weather.date
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsv.weather.city_id
     *
     * @return the value of jsv.weather.city_id
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsv.weather.city_id
     *
     * @param cityId the value for jsv.weather.city_id
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsv.weather.temp_lo
     *
     * @return the value of jsv.weather.temp_lo
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    public Integer getTempLo() {
        return tempLo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsv.weather.temp_lo
     *
     * @param tempLo the value for jsv.weather.temp_lo
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    public void setTempLo(Integer tempLo) {
        this.tempLo = tempLo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsv.weather.temp_hi
     *
     * @return the value of jsv.weather.temp_hi
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    public Integer getTempHi() {
        return tempHi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsv.weather.temp_hi
     *
     * @param tempHi the value for jsv.weather.temp_hi
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    public void setTempHi(Integer tempHi) {
        this.tempHi = tempHi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsv.weather.prcp
     *
     * @return the value of jsv.weather.prcp
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    public Integer getPrcp() {
        return prcp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsv.weather.prcp
     *
     * @param prcp the value for jsv.weather.prcp
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    public void setPrcp(Integer prcp) {
        this.prcp = prcp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsv.weather.date
     *
     * @return the value of jsv.weather.date
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsv.weather.date
     *
     * @param date the value for jsv.weather.date
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }
}