package ms.MyBatisSample.mapper.jsv;

import java.util.List;
import ms.MyBatisSample.entity.jsv.Cities;
import ms.MyBatisSample.entity.jsv.CitiesExample;
import org.apache.ibatis.annotations.Param;

public interface CitiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsv.cities
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    long countByExample(CitiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsv.cities
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    int deleteByExample(CitiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsv.cities
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    int deleteByPrimaryKey(String cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsv.cities
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    int insert(Cities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsv.cities
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    int insertSelective(Cities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsv.cities
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    List<Cities> selectByExample(CitiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsv.cities
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    Cities selectByPrimaryKey(String cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsv.cities
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    int updateByExampleSelective(@Param("record") Cities record, @Param("example") CitiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsv.cities
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    int updateByExample(@Param("record") Cities record, @Param("example") CitiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsv.cities
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    int updateByPrimaryKeySelective(Cities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsv.cities
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    int updateByPrimaryKey(Cities record);
}