package ms.MyBatisSample.mapper.jsv;

import java.util.List;
import ms.MyBatisSample.entity.jsv.Weather;
import ms.MyBatisSample.entity.jsv.WeatherExample;
import ms.MyBatisSample.entity.jsv.WeatherKey;
import org.apache.ibatis.annotations.Param;

public interface WeatherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsv.weather
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    long countByExample(WeatherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsv.weather
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    int deleteByExample(WeatherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsv.weather
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    int deleteByPrimaryKey(WeatherKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsv.weather
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    int insert(Weather record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsv.weather
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    int insertSelective(Weather record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsv.weather
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    List<Weather> selectByExample(WeatherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsv.weather
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    Weather selectByPrimaryKey(WeatherKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsv.weather
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    int updateByExampleSelective(@Param("record") Weather record, @Param("example") WeatherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsv.weather
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    int updateByExample(@Param("record") Weather record, @Param("example") WeatherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsv.weather
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    int updateByPrimaryKeySelective(Weather record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsv.weather
     *
     * @mbg.generated Sun Feb 11 13:05:06 JST 2018
     */
    int updateByPrimaryKey(Weather record);
}